import jsPDF from 'jspdf';
import 'jspdf-autotable';

// Add ATSN logo as base64 (you can replace this with your actual logo)
const ATSN_LOGO = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjQwIiB2aWV3Qm94PSIwIDAgMTAwIDQwIiBmaWxsPSJub25lIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPgo8cmVjdCB3aWR0aD0iMTAwIiBoZWlnaHQ9IjQwIiByeD0iOCIgZmlsbD0idXJsKCNncmFkaWVudCkiLz4KPGRlZnM+CjxsaW5lYXJHcmFkaWVudCBpZD0iZ3JhZGllbnQiIHgxPSIwJSIgeTE9IjAlIiB4Mj0iMTAwJSIgeTI9IjEwMCUiPgo8c3RvcCBvZmZzZXQ9IjAlIiBzdHlsZT0ic3RvcC1jb2xvcjojOTMzM0Y2O3N0b3Atb3BhY2l0eToxIiAvPgo8c3RvcCBvZmZzZXQ9IjEwMCUiIHN0eWxlPSJzdG9wLWNvbG9yOiNGRjRENEE7c3RvcC1vcGFjaXR5OjEiIC8+CjwvbGluZWFyR3JhZGllbnQ+CjwvZGVmcz4KPHN0eWxlPgp0ZXh0IHsKICBmb250LWZhbWlseTogJ0FyaWFsJywgc2Fucy1zZXJpZjsKICBmb250LXdlaWdodDogYm9sZDsKICBmaWxsOiB3aGl0ZTsKfQo8L3N0eWxlPgo8dGV4dCB4PSI1MCIgeT0iMjUiIGZvbnQtc2l6ZT0iMTQiIHRleHQtYW5jaG9yPSJtaWRkbGUiPkFUU04gQUk8L3RleHQ+Cjwvc3ZnPgo=';

export const generateInvoicePDF = (invoiceData, billingHistory) => {
  const doc = new jsPDF();
  
  // Set up colors
  const primaryColor = '#9333F6';
  const secondaryColor = '#FF4D4A';
  const textColor = '#374151';
  const lightGray = '#F3F4F6';
  
  // Add logo
  doc.addImage(ATSN_LOGO, 'PNG', 20, 20, 40, 16);
  
  // Company info
  doc.setFontSize(20);
  doc.setTextColor(primaryColor);
  doc.text('ATSN AI', 20, 50);
  
  doc.setFontSize(10);
  doc.setTextColor(textColor);
  doc.text('AI-Powered Business Solutions', 20, 58);
  doc.text('Email: services@atsnai.com', 20, 66);
  doc.text('Website: www.atsnai.com', 20, 74);
  
  // Invoice header
  doc.setFontSize(24);
  doc.setTextColor(primaryColor);
  doc.text('INVOICE', 140, 30);
  
  // Invoice details
  doc.setFontSize(10);
  doc.setTextColor(textColor);
  doc.text(`Invoice #: ${invoiceData.id}`, 140, 40);
  doc.text(`Date: ${invoiceData.date}`, 140, 48);
  doc.text(`Status: ${invoiceData.status.toUpperCase()}`, 140, 56);
  
  // Customer info
  doc.setFontSize(12);
  doc.setTextColor(primaryColor);
  doc.text('Bill To:', 20, 90);
  
  doc.setFontSize(10);
  doc.setTextColor(textColor);
  doc.text('Customer Name', 20, 100);
  doc.text('Email Address', 20, 108);
  doc.text('Subscription Plan', 20, 116);
  
  // Line separator
  doc.setDrawColor(primaryColor);
  doc.setLineWidth(0.5);
  doc.line(20, 125, 190, 125);
  
  // Invoice items table
  const tableData = [
    ['Description', 'Plan', 'Amount', 'Status'],
    [
      invoiceData.description,
      invoiceData.plan || 'Monthly',
      `₹${(invoiceData.amount / 100).toFixed(2)}`,
      invoiceData.status.toUpperCase()
    ]
  ];
  
  doc.autoTable({
    startY: 135,
    head: [tableData[0]],
    body: [tableData[1]],
    theme: 'grid',
    headStyles: {
      fillColor: primaryColor,
      textColor: 255,
      fontSize: 10,
      fontStyle: 'bold'
    },
    bodyStyles: {
      textColor: textColor,
      fontSize: 10
    },
    alternateRowStyles: {
      fillColor: lightGray
    },
    margin: { left: 20, right: 20 }
  });
  
  // Total section
  const finalY = doc.lastAutoTable.finalY + 20;
  
  doc.setFontSize(12);
  doc.setTextColor(primaryColor);
  doc.text('Total Amount:', 140, finalY);
  doc.text(`₹${(invoiceData.amount / 100).toFixed(2)}`, 170, finalY);
  
  // Payment info
  doc.setFontSize(10);
  doc.setTextColor(textColor);
  doc.text('Payment Method: Razorpay', 20, finalY + 20);
  doc.text('Payment Status: Completed', 20, finalY + 28);
  doc.text(`Transaction ID: ${invoiceData.id}`, 20, finalY + 36);
  
  // Footer
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(8);
  doc.setTextColor('#9CA3AF');
  doc.text('Thank you for choosing ATSN AI!', 20, pageHeight - 20);
  doc.text('For support, contact us at services@atsnai.com', 20, pageHeight - 15);
  doc.text('This is an automated invoice generated by our system.', 20, pageHeight - 10);
  
  return doc;
};

export const generateBillingHistoryPDF = (billingHistory, userInfo) => {
  const doc = new jsPDF();
  
  // Set up colors
  const primaryColor = '#9333F6';
  const secondaryColor = '#FF4D4A';
  const textColor = '#374151';
  const lightGray = '#F3F4F6';
  
  // Add logo
  doc.addImage(ATSN_LOGO, 'PNG', 20, 20, 40, 16);
  
  // Company info
  doc.setFontSize(20);
  doc.setTextColor(primaryColor);
  doc.text('ATSN AI', 20, 50);
  
  doc.setFontSize(10);
  doc.setTextColor(textColor);
  doc.text('AI-Powered Business Solutions', 20, 58);
  doc.text('Email: services@atsnai.com', 20, 66);
  doc.text('Website: www.atsnai.com', 20, 74);
  
  // Report header
  doc.setFontSize(24);
  doc.setTextColor(primaryColor);
  doc.text('BILLING HISTORY', 140, 30);
  
  // Report details
  doc.setFontSize(10);
  doc.setTextColor(textColor);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 140, 40);
  doc.text(`Customer: ${userInfo?.name || 'N/A'}`, 140, 48);
  doc.text(`Total Transactions: ${billingHistory.length}`, 140, 56);
  
  // Line separator
  doc.setDrawColor(primaryColor);
  doc.setLineWidth(0.5);
  doc.line(20, 85, 190, 85);
  
  // Prepare table data
  const tableData = billingHistory.map(invoice => [
    invoice.id,
    new Date(invoice.date).toLocaleDateString(),
    `₹${(invoice.amount / 100).toFixed(2)}`,
    invoice.status.toUpperCase(),
    invoice.description
  ]);
  
  // Add table
  doc.autoTable({
    startY: 95,
    head: [['Invoice ID', 'Date', 'Amount', 'Status', 'Description']],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: primaryColor,
      textColor: 255,
      fontSize: 10,
      fontStyle: 'bold'
    },
    bodyStyles: {
      textColor: textColor,
      fontSize: 9
    },
    alternateRowStyles: {
      fillColor: lightGray
    },
    margin: { left: 20, right: 20 },
    columnStyles: {
      0: { cellWidth: 30 },
      1: { cellWidth: 25 },
      2: { cellWidth: 25 },
      3: { cellWidth: 20 },
      4: { cellWidth: 60 }
    }
  });
  
  // Summary
  const finalY = doc.lastAutoTable.finalY + 20;
  const totalAmount = billingHistory.reduce((sum, invoice) => sum + invoice.amount, 0);
  const paidCount = billingHistory.filter(invoice => invoice.status === 'completed').length;
  
  doc.setFontSize(12);
  doc.setTextColor(primaryColor);
  doc.text('Summary:', 20, finalY);
  
  doc.setFontSize(10);
  doc.setTextColor(textColor);
  doc.text(`Total Amount: ₹${(totalAmount / 100).toFixed(2)}`, 20, finalY + 15);
  doc.text(`Paid Transactions: ${paidCount}`, 20, finalY + 25);
  doc.text(`Total Transactions: ${billingHistory.length}`, 20, finalY + 35);
  
  // Footer
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(8);
  doc.setTextColor('#9CA3AF');
  doc.text('Thank you for choosing ATSN AI!', 20, pageHeight - 20);
  doc.text('For support, contact us at services@atsnai.com', 20, pageHeight - 15);
  doc.text('This report was generated automatically by our system.', 20, pageHeight - 10);
  
  return doc;
};
