import jsPDF from 'jspdf';
import 'jspdf-autotable';

export const generateInvoicePDF = (invoiceData, billingHistory) => {
  try {
    const doc = new jsPDF();
    
    // Set up colors
    const primaryColor = '#9333F6';
    const textColor = '#374151';
    
    // Header
    doc.setFontSize(24);
    doc.setTextColor(primaryColor);
    doc.text('ATSN AI', 20, 30);
    
    doc.setFontSize(10);
    doc.setTextColor(textColor);
    doc.text('AI-Powered Business Solutions', 20, 40);
    doc.text('Email: services@atsnai.com', 20, 48);
    doc.text('Website: www.atsnai.com', 20, 56);
    
    // Invoice title
    doc.setFontSize(20);
    doc.setTextColor(primaryColor);
    doc.text('INVOICE', 140, 30);
    
    // Invoice details
    doc.setFontSize(10);
    doc.setTextColor(textColor);
    doc.text(`Invoice #: ${invoiceData.id}`, 140, 40);
    doc.text(`Date: ${new Date(invoiceData.date).toLocaleDateString()}`, 140, 48);
    doc.text(`Status: ${invoiceData.status.toUpperCase()}`, 140, 56);
    
    // Customer info
    doc.setFontSize(12);
    doc.setTextColor(primaryColor);
    doc.text('Bill To:', 20, 80);
    
    doc.setFontSize(10);
    doc.setTextColor(textColor);
    doc.text('Customer Name', 20, 90);
    doc.text('Email Address', 20, 98);
    doc.text('Subscription Plan', 20, 106);
    
    // Line separator
    doc.setDrawColor(primaryColor);
    doc.setLineWidth(0.5);
    doc.line(20, 115, 190, 115);
    
    // Invoice items table
    const tableData = [
      ['Description', 'Amount', 'Status'],
      [
        invoiceData.description || 'Subscription Payment',
        `₹${(invoiceData.amount / 100).toFixed(2)}`,
        invoiceData.status.toUpperCase()
      ]
    ];
    
    doc.autoTable({
      startY: 125,
      head: [tableData[0]],
      body: [tableData[1]],
      theme: 'grid',
      headStyles: {
        fillColor: primaryColor,
        textColor: 255,
        fontSize: 10,
        fontStyle: 'bold'
      },
      bodyStyles: {
        textColor: textColor,
        fontSize: 10
      },
      margin: { left: 20, right: 20 }
    });
    
    // Total section
    const finalY = doc.lastAutoTable.finalY + 20;
    
    doc.setFontSize(12);
    doc.setTextColor(primaryColor);
    doc.text('Total Amount:', 140, finalY);
    doc.text(`₹${(invoiceData.amount / 100).toFixed(2)}`, 170, finalY);
    
    // Payment info
    doc.setFontSize(10);
    doc.setTextColor(textColor);
    doc.text('Payment Method: Razorpay', 20, finalY + 20);
    doc.text('Payment Status: Completed', 20, finalY + 28);
    doc.text(`Transaction ID: ${invoiceData.id}`, 20, finalY + 36);
    
    // Footer
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(8);
    doc.setTextColor('#9CA3AF');
    doc.text('Thank you for choosing ATSN AI!', 20, pageHeight - 20);
    doc.text('For support, contact us at services@atsnai.com', 20, pageHeight - 15);
    doc.text('This is an automated invoice generated by our system.', 20, pageHeight - 10);
    
    return doc;
  } catch (error) {
    console.error('Error generating invoice PDF:', error);
    throw new Error('Failed to generate PDF: ' + error.message);
  }
};

export const generateBillingHistoryPDF = (billingHistory, userInfo) => {
  try {
    const doc = new jsPDF();
    
    // Set up colors
    const primaryColor = '#9333F6';
    const textColor = '#374151';
    
    // Header
    doc.setFontSize(24);
    doc.setTextColor(primaryColor);
    doc.text('ATSN AI', 20, 30);
    
    doc.setFontSize(10);
    doc.setTextColor(textColor);
    doc.text('AI-Powered Business Solutions', 20, 40);
    doc.text('Email: services@atsnai.com', 20, 48);
    doc.text('Website: www.atsnai.com', 20, 56);
    
    // Report title
    doc.setFontSize(20);
    doc.setTextColor(primaryColor);
    doc.text('BILLING HISTORY', 140, 30);
    
    // Report details
    doc.setFontSize(10);
    doc.setTextColor(textColor);
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, 140, 40);
    doc.text(`Customer: ${userInfo?.name || 'N/A'}`, 140, 48);
    doc.text(`Total Transactions: ${billingHistory.length}`, 140, 56);
    
    // Line separator
    doc.setDrawColor(primaryColor);
    doc.setLineWidth(0.5);
    doc.line(20, 75, 190, 75);
    
    // Prepare table data
    const tableData = billingHistory.map(invoice => [
      invoice.id,
      new Date(invoice.date).toLocaleDateString(),
      `₹${(invoice.amount / 100).toFixed(2)}`,
      invoice.status.toUpperCase(),
      invoice.description || 'Subscription Payment'
    ]);
    
    // Add table
    doc.autoTable({
      startY: 85,
      head: [['Invoice ID', 'Date', 'Amount', 'Status', 'Description']],
      body: tableData,
      theme: 'grid',
      headStyles: {
        fillColor: primaryColor,
        textColor: 255,
        fontSize: 10,
        fontStyle: 'bold'
      },
      bodyStyles: {
        textColor: textColor,
        fontSize: 9
      },
      margin: { left: 20, right: 20 },
      columnStyles: {
        0: { cellWidth: 30 },
        1: { cellWidth: 25 },
        2: { cellWidth: 25 },
        3: { cellWidth: 20 },
        4: { cellWidth: 60 }
      }
    });
    
    // Summary
    const finalY = doc.lastAutoTable.finalY + 20;
    const totalAmount = billingHistory.reduce((sum, invoice) => sum + invoice.amount, 0);
    const paidCount = billingHistory.filter(invoice => invoice.status === 'completed').length;
    
    doc.setFontSize(12);
    doc.setTextColor(primaryColor);
    doc.text('Summary:', 20, finalY);
    
    doc.setFontSize(10);
    doc.setTextColor(textColor);
    doc.text(`Total Amount: ₹${(totalAmount / 100).toFixed(2)}`, 20, finalY + 15);
    doc.text(`Paid Transactions: ${paidCount}`, 20, finalY + 25);
    doc.text(`Total Transactions: ${billingHistory.length}`, 20, finalY + 35);
    
    // Footer
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(8);
    doc.setTextColor('#9CA3AF');
    doc.text('Thank you for choosing ATSN AI!', 20, pageHeight - 20);
    doc.text('For support, contact us at services@atsnai.com', 20, pageHeight - 15);
    doc.text('This report was generated automatically by our system.', 20, pageHeight - 10);
    
    return doc;
  } catch (error) {
    console.error('Error generating billing history PDF:', error);
    throw new Error('Failed to generate PDF: ' + error.message);
  }
};