-- Created_Content Table
-- Simple table to store content generated by Leo Content Generation
-- No campaign logic - just stores generated content directly

CREATE TABLE IF NOT EXISTS created_content (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    platform TEXT,
    content_type TEXT NOT NULL, -- post, reel, video, story, carousel, blog, email, whatsapp, ads
    title TEXT,
    content TEXT NOT NULL,
    hashtags TEXT[] DEFAULT '{}',
    images TEXT[] DEFAULT '{}', -- Array of image URLs
    status TEXT DEFAULT 'generated', -- generated, draft, published
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE created_content ENABLE ROW LEVEL SECURITY;

-- RLS Policies for created_content
CREATE POLICY "Users can view own created content" ON created_content
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own created content" ON created_content
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own created content" ON created_content
    FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own created content" ON created_content
    FOR DELETE USING (auth.uid() = user_id);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_created_content_user_id ON created_content(user_id);
CREATE INDEX IF NOT EXISTS idx_created_content_platform ON created_content(platform);
CREATE INDEX IF NOT EXISTS idx_created_content_content_type ON created_content(content_type);
CREATE INDEX IF NOT EXISTS idx_created_content_created_at ON created_content(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_created_content_status ON created_content(status);

-- Create function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_created_content_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create trigger to automatically update updated_at
CREATE TRIGGER update_created_content_updated_at BEFORE UPDATE ON created_content
    FOR EACH ROW EXECUTE FUNCTION update_created_content_updated_at_column();

